export const GAMES_OPTION_COMPLETION_DESC = "GAMES_OPTION_COMPLETION_DESC";
export const GAMES_OPTION_COMPLETION_ASC = "GAMES_OPTION_COMPLETION_ASC";
export const GAMES_OPTION_COMPLETION_STARTED =
  "GAMES_OPTION_COMPLETION_STARTED";
export const GAMES_OPTION_COMPLETION_PINNED = "GAMES_OPTION_COMPLETION_PINNED";

export const FILTER_OPTIONS_GAMES_PAGE = [
  {
    id: GAMES_OPTION_COMPLETION_STARTED,
    title: "Sort By Started",
  },
  {
    id: GAMES_OPTION_COMPLETION_DESC,
    title: "Sort By Completion [High to Low]",
  },
  {
    id: GAMES_OPTION_COMPLETION_ASC,
    title: "Sort By Completion [Low to High]",
  },
];

export const GAME_OPTION_PERCENTAGE_DESC = "GAME_OPTION_PERCENTAGE_DESC";
export const GAME_OPTION_PERCENTAGE_ASC = "GAME_OPTION_PERCENTAGE_ASC";
export const GAME_OPTION_PERCENTAGE_DESC_UNLOCKED =
  "GAME_OPTION_PERCENTAGE_DESC_UNLOCKED";
export const GAME_OPTION_PERCENTAGE_ASC_UNLOCKED =
  "GAME_OPTION_PERCENTAGE_ASC_UNLOCKED";
export const GAME_OPTION_PERCENTAGE_DESC_LOCKED =
  "GAME_OPTION_PERCENTAGE_DESC_LOCKED";
export const GAME_OPTION_PERCENTAGE_ASC_LOCKED =
  "GAME_OPTION_PERCENTAGE_ASC_LOCKED";
export const GAME_OPTION_PERCENTAGE_DESC_UNLOCKTIME =
  "GAME_OPTION_PERCENTAGE_DESC_UNLOCKTIME";
export const GAME_OPTION_PERCENTAGE_ASC_UNLOCKTIME =
  "GAME_OPTION_PERCENTAGE_ASC_UNLOCKTIME";

export const FILTER_OPTIONS_GAME_PAGE = [
  {
    id: GAME_OPTION_PERCENTAGE_DESC,
    title: "Sort By Easy All",
  },
  {
    id: GAME_OPTION_PERCENTAGE_ASC,
    title: "Sort By Hard All",
  },
  {
    id: GAME_OPTION_PERCENTAGE_DESC_UNLOCKED,
    title: "Sort By Easy Unlocked",
  },
  {
    id: GAME_OPTION_PERCENTAGE_ASC_UNLOCKED,
    title: "Sort By Hard Unlocked",
  },
  {
    id: GAME_OPTION_PERCENTAGE_DESC_LOCKED,
    title: "Sort By Easy Locked",
  },
  {
    id: GAME_OPTION_PERCENTAGE_ASC_LOCKED,
    title: "Sort By Hard Locked",
  },
  {
    id: GAME_OPTION_PERCENTAGE_DESC_UNLOCKTIME,
    title: "Sort By Recently Unlocked",
  },
  {
    id: GAME_OPTION_PERCENTAGE_ASC_UNLOCKTIME,
    title: "Sort By Oldest Unlocked",
  },
];
