export const GAMES_OPTION_COMPLETION_DESC = "GAMES_OPTION_COMPLETION_DESC";
export const GAMES_OPTION_COMPLETION_ASC = "GAMES_OPTION_COMPLETION_ASC";
export const GAMES_OPTION_COMPLETION_STARTED =
  "GAMES_OPTION_COMPLETION_STARTED";
export const GAMES_OPTION_COMPLETION_PINNED = "GAMES_OPTION_COMPLETION_PINNED";

export const FILTER_OPTIONS_GAMES_PAGE = [
  {
    id: GAMES_OPTION_COMPLETION_STARTED,
    title: "Sort By Started",
  },
  {
    id: GAMES_OPTION_COMPLETION_DESC,
    title: "Sort By Completion [High to Low]",
  },
  {
    id: GAMES_OPTION_COMPLETION_ASC,
    title: "Sort By Completion [Low to High]",
  },
];

export const GAME_OPTION_PERCENTAGE_DESC = "GAME_OPTION_PERCENTAGE_DESC";

export const FILTER_OPTIONS_GAME_PAGE = [
  {
    id: GAME_OPTION_PERCENTAGE_DESC,
    title: "Sort By Easy",
  },
];
