export const FETCH_ALL_GAMES_REQUEST = "FETCH_ALL_GAMES_REQUEST";
export const FETCH_ALL_GAMES_SUCCESS = "FETCH_ALL_GAMES_SUCCESS";
export const FETCH_ALL_GAMES_ERROR = "FETCH_ALL_GAMES_ERROR";

export const GAMES_FILTER_CHANGED = "GAMES_FILTER_CHANGED";
export const GAMES_SEARCH_CHANGED = "GAMES_SEARCH_CHANGED";

export const GAME_FILTER_CHANGED = "GAME_FILTER_CHANGED";
export const GAME_SEARCH_CHANGED = "GAME_SEARCH_CHANGED";

export const THEME_ID = "THEME_ID";

export const ADD_PINNED_GAME = "ADD_PINNED_GAME";
export const REMOVE_PINNED_GAME = "REMOVE_PINNED_GAME";

export const SET_HIDDEN_DATA = "SET_HIDDEN_DATA";
export const ADD_JOURNAL_GAME_ACHIEVEMENT = "ADD_JOURNAL_GAME_ACHIEVEMENT";

export const GAME_DATA_REFRESH = "GAME_DATA_REFRESH";
export const LAST_SELECTED_GAME = "LAST_SELECTED_GAME";

export const SET_RARITY_FILTER_FOR_GAME = "SET_RARITY_FILTER_FOR_GAME";
export const SET_OPACITY_UNLOCKED_ACHIEVEMENT =
  "SET_OPACITY_UNLOCKED_ACHIEVEMENT";

export const SET_PHASE_ADDED_GAME = "SET_PHASE_ADDED_GAME";
export const UPDATE_PHASE_ACHIEVEMENT = "UPDATE_PHASE_ACHIEVEMENT";

export const SET_PHASE1_ACHIEVEMENTS = "SET_PHASE1_ACHIEVEMENTS";
export const SET_PHASE2_ACHIEVEMENTS = "SET_PHASE2_ACHIEVEMENTS";
export const SET_PHASE3_ACHIEVEMENTS = "SET_PHASE3_ACHIEVEMENTS";
export const SET_PHASE4_ACHIEVEMENTS = "SET_PHASE4_ACHIEVEMENTS";
export const SET_PHASE5_ACHIEVEMENTS = "SET_PHASE5_ACHIEVEMENTS";
export const SET_PHASE6_ACHIEVEMENTS = "SET_PHASE6_ACHIEVEMENTS";

export const SET_PHASE1_SEARCH = "SET_PHASE1_SEARCH";
export const SET_PHASE2_SEARCH = "SET_PHASE2_SEARCH";
export const SET_PHASE3_SEARCH = "SET_PHASE3_SEARCH";
export const SET_PHASE4_SEARCH = "SET_PHASE4_SEARCH";
export const SET_PHASE5_SEARCH = "SET_PHASE5_SEARCH";
export const SET_PHASE6_SEARCH = "SET_PHASE6_SEARCH";

export const RESET_KANBAN_BOARD = "RESET_KANBAN_BOARD";
export const SET_PLANNER_VIEW_TYPE = "SET_PLANNER_VIEW_TYPE";
export const SET_PLANNER_UNLOCKED_TYPE = "SET_PLANNER_UNLOCKED_TYPE";

export const SHOW_HISTORY_ACHIEVEMENTS = "SHOW_HISTORY_ACHIEVEMENTS";
export const HIDE_HISTORY_ACHIEVEMENTS = "HIDE_HISTORY_ACHIEVEMENTS";

export const SHOW_JOURNAL_RIGHTSIDEBAR = "SHOW_JOURNAL_RIGHTSIDEBAR";
export const HIDE_JOURNAL_RIGHTSIDEBAR = "HIDE_JOURNAL_RIGHTSIDEBAR";
export const TOGGLE_JOURNAL_RIGHTSIDEBAR = "TOGGLE_JOURNAL_RIGHTSIDEBAR";
