export const FETCH_ALL_GAMES_REQUEST = "FETCH_ALL_GAMES_REQUEST";
export const FETCH_ALL_GAMES_SUCCESS = "FETCH_ALL_GAMES_SUCCESS";
export const FETCH_ALL_GAMES_ERROR = "FETCH_ALL_GAMES_ERROR";

export const GAMES_FILTER_CHANGED = "GAMES_FILTER_CHANGED";
export const GAMES_SEARCH_CHANGED = "GAMES_SEARCH_CHANGED";
